### ISSUE TITLE
Allow multiple compression strategies

### ISSUE THREAD

**Issue by lukemelia** [DockYard/ember-cli-deploy-compress#1]
Proposed API:

`keep: false`: Replace the original files with the compressed files. If more than one compression is specified, the first one will be used to replace the original files.
`keep: true`: Keep the original files and and generate separate compressed  files with appropriate extensions
`compression: ['best']`: Use the browser targets config to select between gzip and brotli compression (this is the default
`compression: ['gzip','brotli']`: Compress using both gzip and brotli

**Comment by cibernox** [comment]
Closed by #2
